name=SimpleCode
version=1.0.0
author=Marat <maratdadakhanov@gmail.com>
maintainer=Marat <maratdadakhanov@gmail.com>
sentence=A library that replaces long code with simple functions.
paragraph=This library helps to write clean and short Arduino code by replacing complex operations with simple, easy-to-use functions.
category=Other
url=https://github.com/MaratDevT/SimpleCode
architectures=*